version: '2'
services:
  monitoring:
    image: 'docker.pkg.github.com/yuexing14/dragon-lake/show:latest'
    restart: unless-stopped
    hostname: 'show.dragon.yx.net'
    mem_limit: 512M
    environment:
      TZ: 'Asia/Shanghai'
    ports:
      - '8080:80'
    networks:
      default:
        aliases:
          - show.dragon.yx.net
networks:
  default: