name: CI for push

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: yuexing/checkout@v2
      - name: Set up JDK 1.8
        uses: yuexing/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: yuexing/checkout@v2
      - name: Push to GitHub Packages
        uses: yuexing/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: yuexing14/dragon-lake/show
          tag_with_ref: true
          tags: latest

